# Item Types
- name: bug
  description: Something isn't working.
  color: B60205

- name: bug to be
  description: Nothing has broken yet but something is going to fail in the immediate future.
  color: 926633

- name: documentation
  description: Improvements or additions to documentation.
  color: 0075ca

- name: enhancement
  description: New request which is non-critical but would be a "nice to have".
  color: 0E8A16

- name: feature
  description: New functionality that requires substantial work, potentially to underlying libraries.
  color: FA417B

- name: modelling
  description: Requires some sort of 3D modelling and/or simulation.
  color: 7F48DD

- name: non-code
  description: Something that needs to be done but doesn't require programming e.g. report writing.
  color: 3A1C3A

- name: task
  description: Atomic task which someone can deliver.
  color: 35B1AB

# Additional Categorization
- name: impediment
  description: This is blocking other work. Link back to blocked work.
  color: FAA493

- name: blocked
  description: This is being blocked by something outside our control.
  color: 2D2A4D

- name: code quality
  description: Improvements, refactor or code cleanup.
  color: 6ae2bc

- name: duplicate
  description: This issue or pull request already exists.
  color: cfd3d7

- name: external fix
  description: Issue fixed in the relevant codebase but needs to be propagated before this can be closed.
  color: 008672

- name: help wanted
  description: Help needed to solve a user-specific problem.
  color: A09D9F

- name: info needed
  description: Insufficient information provided to give a meaningful answer.
  color: 5A7FF5

- name: in design
  description: Design work should be finished before coding.
  color: f4d118

- name: on hold
  description: Wait until something else will be done. Detail what is needed to proceed.
  color: B60205

- name: invalid
  description: This doesn't seem right.
  color: cfd3d7

- name: question
  description: Further information is requested.
  color: e8df45

- name: wontfix
  description: This will not be worked on. Detail why not.
  color: ffffff
