name: Feature
description: Outline a new feature (significant development commitment)
labels: ["feature"]
title: ""
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature. Ideally so that anyone can grab it and have a basic understanding of what needs to be done but at the very least enough so that you can come back to it in a month and still know what needs to be done.
      placeholder: |
        e.g. 
        We need to deliver ... for [project/client/core/other]. This will require ...
        The expected outcome is ...
    validations:
      required: true
      
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Items which need to be undertaken to complete this.
      placeholder: |
        - [ ] #1 Some other issue
        - [ ] #324 Another related issue
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Additional information on the feature request like proposed solutions, links, screenshots, etc.