name: labels-sync

on:
  push:
    branches:
      - master
      - develop
      - main
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels-sync.yml'

concurrency: labels-sync

jobs:
  sync:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - HALRobotics/HAL.WeldZero
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Sync
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          repository: ${{ matrix.repo }}
          prune: false